export const seed = {
  users: [],
  sessions: [],
  projects: [
    {
      id: 'tide',
      title: '潮汐之上',
      type: '长篇',
      genre: '现代言情',
      status: '连载中',
      progress: 42,
      words: '18,342',
      updated: '12 分钟前',
      chapters: 8,
      tone: '克制、清醒、带一点潮湿的浪漫',
      cover: 'cover-tide',
      isActive: true,
    },
    {
      id: 'sword',
      title: '剑道独尊',
      type: '参考书',
      genre: '东方玄幻',
      status: '已拆文',
      progress: 100,
      words: '23 章',
      updated: '昨天',
      chapters: 23,
      tone: '升级、冒险、持续的胜利预期',
      cover: 'cover-sword',
      isActive: false,
    },
    {
      id: 'chang-an',
      title: '长安旧梦',
      type: '短篇',
      genre: '古代言情',
      status: '构思中',
      progress: 16,
      words: '2,406',
      updated: '3 天前',
      chapters: 2,
      tone: '旧城、旧人、来不及说完的话',
      cover: 'cover-changan',
      isActive: false,
    },
  ],
  chapters: {
    tide: [
      { id: 1, title: '雨落在海城', words: '2,184', state: 'done' },
      { id: 2, title: '她没有回头', words: '2,601', state: 'done' },
      { id: 3, title: '一封未寄出的信', words: '2,045', state: 'done' },
      { id: 4, title: '潮汐的方向', words: '3,108', state: 'done' },
      { id: 5, title: '凌晨四点的灯', words: '1,986', state: 'done' },
      { id: 6, title: '不合时宜的重逢', words: '2,716', state: 'done' },
      { id: 7, title: '她说，先到这里', words: '1,856', state: 'done' },
      { id: 8, title: '风从旧码头来', words: '1,846', state: 'current' },
      { id: 9, title: '还没有命名', words: '—', state: 'draft' },
    ],
    sword: [],
    'chang-an': [],
  },
  drafts: {
    tide: '凌晨四点，海城的雨还没有停。\n\n沈知遥站在旧码头的屋檐下，看着潮水一点一点漫过那条生锈的缆绳。她已经等了二十七分钟，手机屏幕亮了又暗，最后只剩下电量不足的红色提醒。\n\n远处有船鸣。\n\n她低头看了一眼那封信，信封边角被雨水洇开，露出里面半行熟悉的字迹。',
    sword: '',
    'chang-an': '',
  },
  ideas: [
    { id: 'idea-1', label: '人物', title: '一个不再相信承诺的人', body: '她把所有重要的东西都写在纸上，因为纸不会临时改口。', color: 'coral', projectId: 'tide' },
    { id: 'idea-2', label: '场景', title: '凌晨四点的旧码头', body: '潮水、未接来电，以及一盏不该亮着的灯。', color: 'teal', projectId: 'tide' },
    { id: 'idea-3', label: '冲突', title: '他带着她以为已经丢掉的东西回来', body: '不是为了复合，是为了让她知道当年发生了什么。', color: 'yellow', projectId: 'tide' },
    { id: 'idea-4', label: '一句话', title: '“我不是原谅你，我只是终于不需要你了。”', body: '适合作为章节末尾的情绪落点。', color: 'purple', projectId: 'tide' },
  ],
}
