export const seed = {
	users: [],
	sessions: [],
	passwordResetTokens: [],
	emailVerificationCodes: [],
	projects: [],
	chapters: {},
	drafts: {},
	editHistory: {},
	writingSessions: {},
	writingTasks: [],
	agentThreads: [],
	aiUsage: [],
	foreshadows: [],
	storyMemories: [],
	skillMarketItems: [],
	skillMarketInstalls: [],
	ideas: [],
};
