export const seed = {
  users: [],
  sessions: [],
  projects: [],
  chapters: {},
  drafts: {},
  editHistory: {},
  writingSessions: {},
  writingTasks: [],
  agentThreads: [],
  aiUsage: [],
  foreshadows: [],
  storyMemories: [],
  ideas: [],
}
