load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "yemu-uu-grep",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    aliases = aliases(),
    crate_name = "yemu_uu_grep",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    version = "17.1.5",
    deps = all_crate_deps(normal = True) + [
        "//crates/yemu-uutils-ctx",
        "//crates/yemu-walker",
    ],
)

rust_test(
    name = "yemu-uu-grep_test",
    crate = ":yemu-uu-grep",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
)
